# Python 이미지 사용
FROM python:3.9.19

# 작업 디렉토리 설정
WORKDIR /usr/src/

# 의존성 파일 복사
COPY ./requirements.txt /usr/src/requirements.txt
COPY ./entrypoint.sh /usr/src/entrypoint.sh
COPY ./apps /usr/src/apps
COPY ./migrations /usr/src/migrations

# pip의 version 갱신
RUN pip install --upgrade pip

# Python 라이브러리 설치
RUN pip install -r requirements.txt

ENTRYPOINT ["bash", "entrypoint.sh"]
