"""empty message

Revision ID: 01bacb4cade3
Revises: 92941952aa95
Create Date: 2024-05-19 10:26:24.024871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01bacb4cade3'
down_revision = '92941952aa95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['elder_id'], ['elder.id'], ),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_questions')
    # ### end Alembic commands ###
