"""empty message

Revision ID: 0762c9344000
Revises: c16fcd478020
Create Date: 2024-05-06 07:07:28.966866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0762c9344000'
down_revision = 'c16fcd478020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
