"""empty message

Revision ID: 11d7f3e460fc
Revises: cc1096c8ef29
Create Date: 2024-06-07 20:41:33.610130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d7f3e460fc'
down_revision = 'cc1096c8ef29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_alarm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_alarm', schema=None) as batch_op:
        batch_op.drop_column('memo')

    # ### end Alembic commands ###
