"""empty message

Revision ID: 52d9a4656f4c
Revises: 
Create Date: 2024-06-11 09:04:43.554134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52d9a4656f4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fall_detect', sa.Boolean(), nullable=True))

    with op.batch_alter_table('medicine_alarm', schema=None) as batch_op:
        batch_op.alter_column('do_alarm',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_alarm', schema=None) as batch_op:
        batch_op.alter_column('do_alarm',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)

    with op.batch_alter_table('elder', schema=None) as batch_op:
        batch_op.drop_column('fall_detect')

    # ### end Alembic commands ###
