"""empty message

Revision ID: 5a72e3a98f7e
Revises: cfdaae70a4b3
Create Date: 2024-05-23 02:39:58.957020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a72e3a98f7e'
down_revision = 'cfdaae70a4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('physical_score', sa.Float(), nullable=True),
    sa.Column('mental_score', sa.Float(), nullable=True),
    sa.Column('social_score', sa.Float(), nullable=True),
    sa.Column('lifestyle_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['elder_id'], ['elder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_evaluation')
    # ### end Alembic commands ###
