"""empty message

Revision ID: 5f49d444c095
Revises: 52d9a4656f4c
Create Date: 2024-06-14 03:38:02.549681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f49d444c095'
down_revision = '52d9a4656f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elder_location', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elder_location', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
