"""empty message

Revision ID: 6bcb47b0c71c
Revises: e055726e57ee
Create Date: 2024-06-06 14:26:26.339052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcb47b0c71c'
down_revision = 'e055726e57ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elder_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'elder', ['elder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('elder_id')

    # ### end Alembic commands ###
