"""empty message

Revision ID: 6f3cca565341
Revises: 6bcb47b0c71c
Create Date: 2024-06-07 00:14:25.393035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3cca565341'
down_revision = '6bcb47b0c71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=False),
    sa.Column('do_alarm', sa.Boolean(), nullable=False),
    sa.Column('alarm_type', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['elder_id'], ['elder.id'], ),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
