"""empty message

Revision ID: 871a4b06aabe
Revises: aa38cab4f75b
Create Date: 2024-05-06 08:32:39.452289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871a4b06aabe'
down_revision = 'aa38cab4f75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_code')
    # ### end Alembic commands ###
