"""empty message

Revision ID: 877a6d9d517b
Revises: c8adee89067d
Create Date: 2024-05-21 02:52:05.722442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877a6d9d517b'
down_revision = 'c8adee89067d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counseling_type', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elder', schema=None) as batch_op:
        batch_op.drop_column('counseling_type')

    # ### end Alembic commands ###
