"""empty message

Revision ID: 8da4682c14c5
Revises: 6f3cca565341
Create Date: 2024-06-07 08:22:24.180943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da4682c14c5'
down_revision = '6f3cca565341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addScheduleFromProtectorAlarm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('addMessageFromProtectorAlarm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isFallDetect', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isGetWellnessQuestion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('makeWellnessReport', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('detectFallEvent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alarmFallSuspicious', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('realTimeFallReport', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isCallAlarm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('choiceVoice', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('memo', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elder', schema=None) as batch_op:
        batch_op.drop_column('memo')
        batch_op.drop_column('choiceVoice')
        batch_op.drop_column('isCallAlarm')
        batch_op.drop_column('realTimeFallReport')
        batch_op.drop_column('alarmFallSuspicious')
        batch_op.drop_column('detectFallEvent')
        batch_op.drop_column('makeWellnessReport')
        batch_op.drop_column('isGetWellnessQuestion')
        batch_op.drop_column('isFallDetect')
        batch_op.drop_column('addMessageFromProtectorAlarm')
        batch_op.drop_column('addScheduleFromProtectorAlarm')

    # ### end Alembic commands ###
