"""empty message

Revision ID: 8e409a21e0ae
Revises: 8da4682c14c5
Create Date: 2024-06-07 08:42:49.262627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e409a21e0ae'
down_revision = '8da4682c14c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completeScheduleAlarm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fallDetectAlarm', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('getReportAlarm', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardian', schema=None) as batch_op:
        batch_op.drop_column('getReportAlarm')
        batch_op.drop_column('fallDetectAlarm')
        batch_op.drop_column('completeScheduleAlarm')

    # ### end Alembic commands ###
