"""empty message

Revision ID: 92941952aa95
Revises: 94e37d44e347
Create Date: 2024-05-06 20:55:51.536493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92941952aa95'
down_revision = '94e37d44e347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dummy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_column('dummy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dummy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy', mysql.VARCHAR(length=32), nullable=False))
        batch_op.drop_column('time')

    # ### end Alembic commands ###
