"""empty message

Revision ID: 965a84647e52
Revises: 5a72e3a98f7e
Create Date: 2024-05-23 02:48:08.037651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965a84647e52'
down_revision = '5a72e3a98f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_evaluation', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_elder_month', ['elder_id', 'month'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_evaluation', schema=None) as batch_op:
        batch_op.drop_constraint('unique_elder_month', type_='unique')

    # ### end Alembic commands ###
