"""empty message

Revision ID: 9df5d9134b4c
Revises: 6ea30c128c7d
Create Date: 2024-06-03 06:56:08.648083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df5d9134b4c'
down_revision = '6ea30c128c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_verification_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone_verification_code', schema=None) as batch_op:
        batch_op.drop_column('valid_date')

    # ### end Alembic commands ###
