"""empty message

Revision ID: aa38cab4f75b
Revises: 6746a7a54687
Create Date: 2024-05-06 07:19:39.285965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa38cab4f75b'
down_revision = '6746a7a54687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('elder_to_guardian_relation', sa.String(length=50), nullable=True),
    sa.Column('guardian_to_elder_relation', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['elder_id'], ['elder.id'], ),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('expiration_time', mysql.DATETIME(), nullable=False),
    sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('care_relationship')
    # ### end Alembic commands ###
