"""empty message

Revision ID: b85cfcf356c9
Revises: 9df5d9134b4c
Create Date: 2024-06-04 02:32:57.479996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b85cfcf356c9'
down_revision = '9df5d9134b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotion', sa.Integer(), nullable=True))
        batch_op.alter_column('answer',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_constraint('question_answer_ibfk_2', type_='foreignkey')
        batch_op.drop_column('guardian_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('question_answer_ibfk_2', 'guardian', ['guardian_id'], ['id'])
        batch_op.alter_column('answer',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('emotion')

    # ### end Alembic commands ###
