"""empty message

Revision ID: bb2261f0295c
Revises: d73813af6cc9
Create Date: 2024-05-05 17:40:51.502864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2261f0295c'
down_revision = 'd73813af6cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.drop_index('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=True)

    # ### end Alembic commands ###
