"""empty message

Revision ID: c16fcd478020
Revises: bb2261f0295c
Create Date: 2024-05-06 07:04:54.112678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c16fcd478020'
down_revision = 'bb2261f0295c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('residence', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('current_location', sa.String(length=255), nullable=True))
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('birthdate',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_index('ix_users_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_name', ['name'], unique=False)
        batch_op.alter_column('birthdate',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_column('current_location')
        batch_op.drop_column('residence')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
