"""empty message

Revision ID: cc1096c8ef29
Revises: 8e409a21e0ae
Create Date: 2024-06-07 19:27:24.210800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1096c8ef29'
down_revision = '8e409a21e0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('care_relationship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo_elder', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('memo_guardian', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('care_relationship', schema=None) as batch_op:
        batch_op.drop_column('memo_guardian')
        batch_op.drop_column('memo_elder')

    # ### end Alembic commands ###
