"""empty message

Revision ID: cfdaae70a4b3
Revises: 877a6d9d517b
Create Date: 2024-05-22 13:54:09.270140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdaae70a4b3'
down_revision = '877a6d9d517b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counseling_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('counseling_type', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['elder_id'], ['elder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counseling_score')
    # ### end Alembic commands ###
