"""empty message

Revision ID: e055726e57ee
Revises: a63f92fde119
Create Date: 2024-06-06 14:25:29.239031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e055726e57ee'
down_revision = 'a63f92fde119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('start_day', sa.Integer(), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('end_month', sa.Integer(), nullable=False),
    sa.Column('end_day', sa.Integer(), nullable=False),
    sa.Column('end_hour', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=64), nullable=True),
    sa.Column('do_alarm', sa.Integer(), nullable=False),
    sa.Column('confirm_alarm_minute', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
